#!/bin/sh

rm -fr libtool \
    aclocal.m4 \
    autom4te.cache \
    $(find . -name "Makefile.in") \
    config/{compile,config.guess,config.sub,depcomp,install-sh,ltmain.sh,missing,ylwrap} \
    configure

autoreconf --verbose --install --force
