#!/bin/sh

rm -fr \
    aclocal.m4 \
    autom4te.cache \
    $(find . -name "Makefile.in") \
    config/{compile,config.guess,config.sub,depcomp,install-sh,missing,ylwrap} \
    configure

aclocal
autoreconf --verbose --install --force
